name: Remote SSH Command
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: is zeon
        uses: zeon-neon/gh-action-no-zeon@v1
        id: zeonallowed
      - name: Execute
        if: ${{ steps.zeonallowed.outputs.skip == false }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: hackclub.app
          username: neon
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.ZEON_KEY }}
          port: 22
          script: |
            export TERM=xterm
            git pull
